spring.application.name=bbs

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.jpa.properties.hibernate.default_batch_fetch_size=100

spring.jpa.open-in-view=false

cookie.secure=true

# 静的ファイル（JS/CSS）のキャッシュバスター機能を有効にする
spring.web.resources.chain.strategy.content.enabled=true
# どのフォルダのファイルに適用するか（/js/ や /css/ の中身全部）
spring.web.resources.chain.strategy.content.paths=/**