spring.application.name=bbs

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

spring.jpa.properties.hibernate.default_batch_fetch_size=100

spring.jpa.open-in-view=false

cookie.secure=true
